
[auth]
site_url = "https://fit-zone-7d3n.vercel.app"
additional_redirect_urls = [
  "http://localhost:5173/**",
  "http://localhost:5173/auth/callback",
  "https://fit-zone-7d3n.vercel.app",
  "https://fit-zone-7d3n.vercel.app/**",
  "https://fit-zone-7d3n.vercel.app/auth/callback",
  "https://fit-zone-7d3n-rohithkannan362-rks-projects.vercel.app/**",
  "https://fit-zone-7d3n-rohithkannan362-rks-projects.vercel.app/auth/callback",
  "https://fit-*-zone-7d3n-rohithkannan362-rks-projects.vercel.app/**"
]

[functions.create-payment-order]
enabled = true
verify_jwt = false
import_map = "./functions/create-payment-order/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-payment-order/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-payment-order/*.html" ]

[functions.payment-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/payment-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/payment-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/payment-webhook/*.html" ]

[functions.process-reminders]
enabled = true
verify_jwt = false
import_map = "./functions/process-reminders/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/process-reminders/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/process-reminders/*.html" ]
